### ISSUE TITLE
Boxplots including 'Frequency Histogramms' from the last FROH

### ISSUE THREAD

**Issue by JanEllenberger** [hortibonn/Plotting-High-Dimensional-Data#6]
@marruett would you mind sharing the code for those figures with us? 
I might wanna use it and @EduardoFernandezC also wants to use and possibly improve it.

And a general question: Is this "issue tab" the place for requests like this?

**Comment by CWWhitney** [comment]
@JanEllenberger Yes, this is the place for questions like this.
@marruett would you like to create a pull request?
All: I responded to the email thread and it did not post to issues (had to log in and write this manually)
